### ISSUE TITLE
Latest version is broken

### ISSUE THREAD

**Issue by awoimbee** [mithro/actions-includes#23]
non existing `include_action` referenced: https://github.com/mithro/actions-includes/blob/bb6134d1033d42e7d591645a756a3c49442be480/actions_includes/__init__.py#L963

line 954: set **only if running in this repo**
line 963: used

**Comment by awoimbee** [comment]
`pip install actions-includes==0.0.post102` to continue using this project

**Comment by mithro** [comment]
I think I have fixed this now. I guess I should add a test for this pathway somehow?
